name: Bump Dependencies

on:
  repository_dispatch:
    types: [bump-dependencies]

jobs:
  bump-dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
      with:
        egress-policy: audit

    - uses: spinnaker/bumpdeps@e80ad47c2a38b2c0709ab0ee9b916a263af05b6d # master
      with:
        ref: ${{ github.event.client_payload.ref }}
        key: clouddriverVersion
        repositories: halyard
      env:
        GITHUB_OAUTH: ${{ secrets.SPINNAKER_GITHUB_TOKEN }}
